### ISSUE TITLE
import capitalize from './capitalize.js';

### ISSUE THREAD

**Issue by pomazanbohdan** [niama-strategies/niama#34]
1. quasar create
2. quasar dev
work
3. quasar ext add @niama/starter
4. dev:client
error 

`app:extension Running "@niama/starter" Quasar App Extension... +0ms
 app:extension Running "@niama/pug" Quasar App Extension... +8ms
 app:extension Running "@niama/i18n" Quasar App Extension... +1ms
 app:extension Running "@niama/ts" Quasar App Extension... +41ms
 app:extension Running "@niama/api" Quasar App Extension... +1ms
(node:29111) UnhandledPromiseRejectionWarning: /home/centos/test/node_modules/lodash-es/camelCase.js:1
import capitalize from './capitalize.js';
       ^^^^^^^^^^

  SyntaxError: Unexpected identifier

  - loader.js:723 Module._compile
    internal/modules/cjs/loader.js:723:23

  - loader.js:789 Object.Module._extensions..js
    internal/modules/cjs/loader.js:789:10

  - loader.js:653 Module.load
    internal/modules/cjs/loader.js:653:32

  - loader.js:593 tryModuleLoad
    internal/modules/cjs/loader.js:593:12

  - loader.js:585 Function.Module._load
    internal/modules/cjs/loader.js:585:3

  - loader.js:692 Module.require
    internal/modules/cjs/loader.js:692:17

  - helpers.js:25 require
    internal/modules/cjs/helpers.js:25:18

  - index.js:10 Object.<anonymous>
    [test]/[@niama]/core/dist/index.js:10:33

  - loader.js:778 Module._compile
    internal/modules/cjs/loader.js:778:30

  - loader.js:789 Object.Module._extensions..js
    internal/modules/cjs/loader.js:789:10

(node:29111) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:29111) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Done in 2.39s.
`

**Comment by gbouteiller** [comment]
Hello @pomazanbohdan, 
I'm actively working on the repo so sorry for the inconvenience. It should work now!
